to get rid of warning with the Intel compiler (see below)
../../../src/molden/compute_transforms.cc(36): error #858: type qualifier on return type is meaningless
      const double comb(const int i, const int j) const {

The first const means nothing in the current C++ standard, perhaps. Therefore it seems we need to throw it away.